---
  - name: test playbook
    remote_user: "{{ ansible_user }}"
    gather_facts: yes
    hosts:
      - "{{ host }}"
    become: yes
    become_user: root
    become_method: sudo
    vars:
      ssh_root_pwd: "netease"
      zstack_mysql_root_pwd: "netease"
      # if you want to use defined apt sources, change it to 'no'
      use_apt_sources_list: yes
      ntp_servers:
        - hz.ntp.x.netease.com
        - ntp.x.netease.com
      # if you want to use defined ntp server addrs, change it to 'yes'
      use_ntp_servers: yes
      use_dns_servers: yes
      dns_servers:
        - "192.168.130.33"
        - "192.168.130.31"
      # zstack example tinny image path is in roles/zk_start/files/zstack-image-1.4.qcow2
      # you can download it first and put it to the path before
      trans_tinny_image: no
      # zstack example tinny image path is in roles/zk_start/files/zstack-virtualrouter-1.1.0.qcow2
      # you can download it first and put it to the path before
      trans_vr_image: no


    roles:
      - test_role
