---
  # Notice:
  #   open remote sshd and permit root user to login
  #
  #   tips:
  #   compute node must be permit to root remote connnect when we add a host
  #   modify the sshd configure file '/etc/ssh/sshd_config', 'PermitRootLogin no' -> 'PermitRootLogin yes'
  #   and add the root password, passwd root

  # Usage:
  # ansible-playbook -vv playbooks/zk_config_sshd.yml -c paramiko --extra-vars 'host=zk-server ansible_port=<ssh-old-port>'

  - name: deploy zstack POC env
    remote_user: "{{ ansible_user }}"
    gather_facts: yes
    hosts:
      - "{{ host }}"
    become: yes
    become_user: root
    become_method: sudo

    roles:
      - config_sshd
