---
  # Notice:
  #   This is zstack ansible deployment mini project.
  #   Anybody can use it to deploy a complete zstack POC environment all on a single Linux machine.
  #   But just support Debian 8.x system.

  # Usage:
  # ansible-playbook -vv playbooks/zk_deploy_single.yml -c paramiko  --extra-vars 'host=zk-server ansible_port=<ssh-port>'

  - name: deploy zstack POC env
    remote_user: "{{ ansible_user }}"
    gather_facts: yes
    hosts:
      - "{{ host }}"
    become: yes
    become_user: root
    become_method: sudo

    roles:
      # - zk_base_env
      # - zk_restart_os
      # - zk_mysql_rabbitmq
      - zk_mgmnode
      - zk_http_nfs
      - zk_repair_code
