---
- debug: msg="this is CentOS task."

- name: check os version
  fail: msg="your system version is {{ ansible_distribution_major_version|int }}, cannot be supported !!"
  when: ansible_distribution_major_version|int != 7

- name: stop the firewall
  service: name=firewalld enabled=no state=stopped
